spring:
  datasource:
    url: ${APP_DATASOURCE_URL}
    username: ${APP_DATASOURCE_USERNAME}
    password: ${APP_DATASOURCE_PASSWORD}
  data:
    redis:
      host: ${APP_REDIS_HOST}
      port: ${APP_REDIS_PORT:6379}
      password: ${APP_REDIS_PASSWORD:}
      database: ${APP_REDIS_DATABASE:0}

app:
  cors:
    allowed-origins: ${APP_CORS_ALLOWED_ORIGINS}
  auth:
    jwt-secret: ${APP_AUTH_JWT_SECRET}
